import { DevtoolsProvider } from "@providers/devtools";
import { useNotificationProvider } from "@refinedev/antd";
import { GitHubBanner, Refine } from "@refinedev/core";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";
import routerProvider from "@refinedev/nextjs-router";
import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";

import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ColorModeContextProvider } from "@contexts/color-mode";
import { authProvider } from "@providers/auth-provider";
import { dataProvider } from "@providers/data-provider";
import "@refinedev/antd/dist/reset.css";
import { FaAddressBook, FaHome, FaEnvelope, FaStar, FaChartBar, FaCog } from "react-icons/fa";

export const metadata: Metadata = {
  title: "Immo",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");
  const defaultMode = theme?.value === "dark" ? "dark" : "light";

  return (
    <html lang="en">
      <body>
        <Suspense>
          {/* <GitHubBanner /> */}
          <RefineKbarProvider>
            <AntdRegistry>
              <ColorModeContextProvider defaultMode={defaultMode}>
                <DevtoolsProvider>
                  <Refine
                    routerProvider={routerProvider}
                    dataProvider={dataProvider}
                    notificationProvider={useNotificationProvider}
                    authProvider={authProvider}
                    resources={[
                      {
                        name: "users",
                        list: "/users",
                        create: "/users/create",
                        edit: "/users/edit/:id",
                        show: "/users/show/:id",
                        meta: {
                          icon: <FaAddressBook />,
                          canDelete: true,
                        },
                      },
                      {
                        name: "properties",
                        list: "/properties",
                        create: "/properties/create",
                        edit: "/properties/edit/:id",
                        show: "/properties/show/:id",
                        meta: {
                          icon: <FaHome />,
                          canDelete: true,
                        },
                      },
                      {
                        name: "messages",
                        list: "/messages",
                        create: "/messages/create",
                        edit: "/messages/edit/:id",
                        show: "/messages/show/:id",
                        meta: {
                          icon: <FaEnvelope />,
                          canDelete: true,
                        },
                      },
                      {
                        name: "reviews",
                        list: "/reviews",
                        create: "/reviews/create",
                        edit: "/reviews/edit/:id",
                        show: "/reviews/show/:id",
                        meta: {
                          hide: true,
                          icon: <FaStar />,
                          canDelete: true,
                        },
                      },
                      {
                        name: "dashboard",
                        list: "/dashboard",
                        create: "/dashboard/create",
                        edit: "/dashboard/edit/:id",
                        show: "/dashboard/show/:id",
                        meta: {
                          hide: true,
                          icon: <FaChartBar />,
                          canDelete: true,
                        },
                      },
                      {
                        name: "administration",
                        list: "/administration",
                        create: "/administration/create",
                        edit: "/administration/edit/:id",
                        show: "/administration/show/:id",
                        meta: {
                          hide: true,
                          icon: <FaCog />,
                          canDelete: true,
                        },
                      },
                      {
                        name: "blog_posts",
                        list: "/blog-posts",
                        create: "/blog-posts/create",
                        edit: "/blog-posts/edit/:id",
                        show: "/blog-posts/show/:id",
                        meta: {
                          hide: true,
                          canDelete: true,
                        },
                      },
                      {
                        name: "categories",
                        list: "/categories",
                        create: "/categories/create",
                        edit: "/categories/edit/:id",
                        show: "/categories/show/:id",
                        meta: {
                          hide: true,
                          canDelete: true,
                        },
                      },
                    ]}
                    options={{
                      syncWithLocation: true,
                      warnWhenUnsavedChanges: true,
                      useNewQueryKeys: true,
                      projectId: "MReDvV-4cK1qz-DsPNNR",
                    }}
                  >
                    {children}
                    <RefineKbar />
                  </Refine>
                </DevtoolsProvider>
              </ColorModeContextProvider>
            </AntdRegistry>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  );
}
